services:
  admin-dashboard:
    container_name: admin-dashboard
    build:
      context: .
      dockerfile: ./Dockerfile
    image: admin_dashboard
    ports:
      - "3000:5173"
    volumes:
      - ./src:/frontend/src
      - ./public:/frontend/public
    command: [ "npm", "run", "dev", "--", "--host" ]